knowledge_graph:
  kg: env(KG:wikidata)
  entities: env(ENTITIES_TYPE:fuzzy)
  properties: env(PROPERTIES_TYPE:embedding)
  info:
    endpoint: env(ENDPOINT:null)

temperature: env(TEMPERATURE:0.4)
min_p: env(MIN_P:null)
top_k: env(TOP_K:null)
top_p: env(TOP_P:0.9)
repeat_penalty: env(REPEAT_PENALTY:null)
do_sample: env(DO_SAMPLE:true)

skeleton_n: env(SKELETON_N:8)
skeleton_top_k: env(SKELETON_TOP_K:3)

selection_top_k: env(SELECTION_TOP_K:10)
constrain: env(CONSTRAIN:true)
backtrack: env(BACKTRACK:true)
rerank: env(RERANK:true)
check_empty: env(CHECK_EMPTY:true)

fill_order: env(FILL_ORDER:triple-wise-entities-then-properties)

improve_skeletons: env(IMPROVE_SKELETONS:false)
improve_threshold: env(IMPROVE_THRESHOLD:0.9)
improve_rounds: env(IMPROVE_ROUNDS:1)
improve_n: env(IMPROVE_N:4)

skeleton_disable_adapter: env(SKELETON_DISABLE_ADAPTER:false)
selection_disable_adapter: env(SELECTION_DISABLE_ADAPTER:false)
validate_disable_adapter: env(VALIDATE_DISABLE_ADAPTER:false)
improve_disable_adapter: env(IMPROVE_DISABLE_ADAPTER:false)
