model: env(MODEL:gpt-5.4-mini)
model_provider: env(MODEL_PROVIDER:openai/responses)
model_endpoint: env(MODEL_ENDPOINT:null)
model_api_key: env(MODEL_API_KEY:null)
model_kwargs:
  reasoning:
    effort: env(REASONING_EFFORT:null)
    summary: env(REASONING_SUMMARY:null)
  text:
    verbosity: env(VERBOSITY:low)

seed: env(SEED:22)

knowledge_graph:
  kg: env(KG:wikidata)
  info:
    endpoint: env(ENDPOINT:null)
