model: env(MODEL:gpt-5.6-terra)
model_provider: env(MODEL_PROVIDER:openai/responses)
model_endpoint: env(MODEL_ENDPOINT:null)
model_api_key: env(MODEL_API_KEY:null)
model_timeout: env(MODEL_TIMEOUT:120)
model_kwargs:
  # for OpenAI models
  reasoning:
    effort: env(REASONING_EFFORT:null)
    summary: env(REASONING_SUMMARY:null)
  text:
    verbosity: env(VERBOSITY:low)
  # for Anthropic models
  # thinking:
  #   type: enabled
  #   budget_tokens: env(THINKING_BUDGET:4096)

max_completion_tokens: env(MAX_TOKENS:16384)
tool_choice: env(TOOL_CHOICE:auto)

task_kwargs:
  cea:
    context_rows: env(CEA_CONTEXT_ROWS:10)

seed: env(SEED:null)

feedback: env(FEEDBACK:false)
know_before_use: env(KNOW_BEFORE_USE:false)
notes_file: env(NOTES_FILE:null)

sparql_connection_timeout: env(SPARQL_CONNECTION_TIMEOUT:6.0)
sparql_query_timeout: env(SPARQL_QUERY_TIMEOUT:30.0)
sparql_read_timeout: env(SPARQL_READ_TIMEOUT:10.0)

fn_set: env(FN_SET:all)
list_k: env(LIST_K:10)
search_k: env(SEARCH_K:10)
result_max_rows: env(RESULT_MAX_ROWS:10)
result_max_columns: env(RESULT_MAX_COLUMNS:10)

force_examples: env(FORCE_EXAMPLES:null)
random_examples: env(RANDOM_EXAMPLES:false)
num_examples: env(NUM_EXAMPLES:3)

knowledge_graphs:
  - kg: wikidata
    examples: env(WD_EXAMPLES:null)
    entities: env(WD_ENT_TYPE:fuzzy)
    properties: env(WD_PROP_TYPE:embedding)
    notes_file: env(WD_NOTES_FILE:null)
  - kg: freebase
  - kg: dblp
  - kg: dbpedia
  - kg: imdb
  - kg: orkg
  - kg: osm-planet
  - kg: uniprot

# server config
port: env(PORT:6789)
max_connections: env(MAX_CONNECTIONS:10)
max_idle_time: env(MAX_IDLE_TIME:300)
max_generation_time: env(MAX_GENERATION_TIME:300)
log_outputs: env(LOG_OUTPUTS:null)
log_file: env(LOG_FILE:null)
share: env(SHARE:null)
rate_limit: env(RATE_LIMIT:null)
rate_limit_window: env(RATE_LIMIT_WINDOW:60)
